blank_issues_enabled: true
contact_links:
  - name: General Discussion
    url: https://github.com/siligam/dummyxarray/discussions
    about: For questions, ideas, or general discussion about the project
